checks:
  method-lines:
    enabled: false

  similar-code:
    enabled: false

plugins:
  eslint:
    enabled: true
    channel: eslint-4
    config:
      extensions:
        - .js
        - .jsx
  markdownlint:
    enabled: true
