rules:
  # object keys must have at least one space after the colon
  key-spacing:
    - 2
    - mode: 'minimum'

  # never use semi-colons
  semi:
    - 2
    - never

  # though we don’t enforce, only use multi spaces for alignment
  no-multi-spaces:
    - 0

  # remove all unused variables
  no-unused-vars:
    - 2
    - argsIgnorePattern: '^_' # ignore vars with a _ prefix (e.g. _foo)

  # For our test files; disable this for sinon-chai’s `foo.should.have.been.calledOnce` signature
  no-unused-expressions:
    - 0

extends: 'airbnb'

parser: 'babel-eslint'

settings:
  import/resolver:
    babel-module: {}

env:
  browser: true
