extends: 'airbnb'

env:
  browser: true
  jest: true

globals:
  chrome: false

rules:
  jsx-a11y/interactive-supports-focus:
    - off

  # ensure consistency when using newlines within a function’s parens
  function-paren-newline:
    - error
    - consistent

  # object keys must have at least one space after the colon
  key-spacing:
    - error
    - mode: 'minimum'

  # allow console use
  no-console:
    - off

  # though we don’t enforce, only use multi spaces for alignment
  no-multi-spaces:
    - off

  # remove all unused variables
  no-unused-vars:
    - error
    - argsIgnorePattern: '^_' # ignore vars with a _ prefix (e.g. _foo)

  # never use semi-colons
  semi:
    - error
    - never

parser: 'babel-eslint'

settings:
  import/resolver:
    babel-module: {}
